apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-account-show
  labels:
    app: azure-account-show
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-account-show
  template:
    metadata:
      labels:
        app: azure-account-show
    spec:
      serviceAccountName: azure-account-show
      containers:
        - name: azure-account-show
          image: ghcr.io/waeltken/azure-account-show/main:latest
          imagePullPolicy: Always
