apiVersion: v1
kind: Service
metadata:
  name: build-and-deploy
  namespace: namespace-workflow-1706191278103
spec:
  type: LoadBalancer
  selector:
    app: build-and-deploy
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000