apiVersion: v1
kind: Service
metadata:
  name: default-workflow-aks
  namespace: azure-account-show
spec:
  type: LoadBalancer
  selector:
    app: default-workflow-aks
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000