name: Trigger auto deployment for nginx

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/nginx-AutoDeployTrigger-0a1c207c-b7a5-4ded-9e70-a23f3f8493de.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.NGINX_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.NGINX_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.NGINX_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: clwaltke.azurecr.io
          registryUsername: ${{ secrets.NGINX_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.NGINX_REGISTRY_PASSWORD }}
          containerAppName: nginx
          resourceGroup: test-ifm-rg
          imageToBuild: clwaltke.azurecr.io/nginx:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


